#!/bin/sh

set -eu

function cleanup_on_error() {
    code="$?"
    rm -rf $EMACS_VERSION | true
    exit $code
}

rm -rf $EMACS_VERSION | true
mkdir $EMACS_VERSION
cp *.el $EMACS_VERSION/


emacs --batch -Q \
      -L /slack \
      -l ./test/setup.el \
      -f batch-byte-compile ./$EMACS_VERSION/*.el \
      || cleanup_on_error

rm -rf $EMACS_VERSION | true

